CREATE DATABASE FUNCDEP
GO
USE FUNCDEP
GO
CREATE TABLE FUNCIONARIO(
CODIGO		INT				NOT NULL,
NOME		VARCHAR(50)		NOT NULL,
SALARIO		NUMERIC(7,2)	NOT NULL
PRIMARY KEY(CODIGO)
)
GO
CREATE TABLE DEPENDENTE(
CODIGO_FUNCIONARIO		INT				NOT NULL,
NOME_DEPENDENTE			VARCHAR(50)		NOT NULL,
SALARIO_DEPENDENTE		NUMERIC(7,2)	NOT NULL
PRIMARY KEY(CODIGO_FUNCIONARIO)
FOREIGN KEY (CODIGO_FUNCIONARIO)
			REFERENCES FUNCIONARIO(CODIGO)
)
GO
CREATE PROCEDURE POPPER
AS
	DECLARE @NOMEF VARCHAR(50),
			@CODIGOINC INT,
			@SALARIO NUMERIC (7,2),
			@I INT,
			@TOTI INT
	SET @I = 0
	SET @TOTI = (RAND()*16)+10
	WHILE(@I <= @TOTI)
	BEGIN
		SET @NOMEF = CONCAT('FUNCIONARIO-',CAST(@I AS VARCHAR(50)))
		SET @CODIGOINC = @I
		SET @SALARIO = (RAND()*2989)+180
		INSERT INTO FUNCIONARIO VALUES (@CODIGOINC,@NOMEF,@SALARIO)
		SET @I = @I + 1
	END
GO
EXEC POPPER
GO
SELECT * FROM FUNCIONARIO
GO
CREATE PROCEDURE DEPENDENTEF
AS
	DECLARE @NOMEF VARCHAR(50),
			@CODIGOINC INT,
			@SALARIO NUMERIC (7,2),
			@I INT,
			@TOTI INT
	SET @I = 0
	SET @TOTI = (RAND()*16)+10
	WHILE(@I <= @TOTI)
	BEGIN
		SET @NOMEF = CONCAT('DEPENDENTE-',CAST(@I AS VARCHAR(50)))
		SET @CODIGOINC = (SELECT F.CODIGO FROM FUNCIONARIO F WHERE F.CODIGO = @I)
		SET @SALARIO = (RAND()*2989)+180
		INSERT INTO DEPENDENTE VALUES (@CODIGOINC,@NOMEF,@SALARIO)
		SET @I = @I + 1
	END
GO
EXEC DEPENDENTEF
GO
SELECT * FROM DEPENDENTE
GO
CREATE FUNCTION FN_TABBER()
RETURNS @TAB TABLE(
NF		VARCHAR(50),
ND		VARCHAR(50),
SF		NUMERIC(7,2),
SD		NUMERIC(7,2)
)
AS
	BEGIN
		INSERT INTO @TAB (NF,ND,SF,SD) SELECT F.NOME,D.NOME_DEPENDENTE,F.SALARIO,D.SALARIO_DEPENDENTE
		FROM FUNCIONARIO F INNER JOIN DEPENDENTE D ON F.CODIGO = D.CODIGO_FUNCIONARIO
		RETURN
	END
GO
--DROP FUNCTION FN_TABBER
--GO
SELECT * FROM FN_TABBER()
GO
CREATE FUNCTION SCAR(@COD INT)
RETURNS INT
AS
	BEGIN
		DECLARE @VAL NUMERIC (7,2),
				@SALF NUMERIC (7,2),
				@SALD NUMERIC (7,2)
		SET @VAL = 0
		SET @SALF = (SELECT F.SALARIO FROM FUNCIONARIO F WHERE F.CODIGO = @COD)
		SET @SALD = (SELECT D.SALARIO_DEPENDENTE FROM DEPENDENTE D WHERE D.CODIGO_FUNCIONARIO = @COD)

		SET @VAL = @SALD + @SALF
		RETURN @VAL
	END
GO
SELECT dbo.SCAR(1) AS FUNC